Error in example code
The `decode` method is used instead of `encode`
```
>>> hash = hashlib.sha256('a').digest()
>>> hex_string = hash.decode('hex')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Non-hexadecimal digit found
>>> hex_string = hash.encode('hex')
>>> hex_string
'ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb'
```